### ISSUE TITLE
Azure AD Credential Login Alternative

### ISSUE THREAD

**Issue by rogueautomation** [test-kitchen/kitchen-azurerm#147]
### Describe the Enhancement:

 We would like to use Azure AD Credentials rather than SPN or MSI credentials.

 ### Describe the Need:

 In certain cases, it may not be feasible to provide each user with SPN information without incurring significant burden to constantly retrieve client secrets from vaults - and for security best practices each user would need a unique service principal that is automatically rotated.

When a device (NOT hosted on the Azure platform) is both Azure AD Hybrid Joined and Microsoft Active Directory (on-premise) joined, using the User-Assigned Managed Identity is not possible for authenticating into the Azure Platform.

In this case, using Azure AD credentials would resolve this.

### Current Alternative

 Currently we can only utilize the AzureRM driver in automated pipelines.

 ### Can We Help You Implement This?:

 We can definitely participate in testing, and potentially in development for this feature.

**Comment by stuartpreston** [comment]
I have thought about this a few times over my time on the project and wanted to add a couple of pointers.

The need for a Service Principal or MSI is obviously because of the automation/non-interactive requirement. If you have an interactive requirement, one way I had been considering was to use the Azure CLI token provider: <https://github.com/Azure/azure-sdk-for-ruby/commit/1e135955dfe72f0a6b282d7239ad14789c322e43> which would let you use `az login` interactively (with a device code auth, or perhaps even SSO).

The fix in the driver could be as simple as falling through to the az provider around here, or rewriting that method properly: https://github.com/test-kitchen/kitchen-azurerm/blob/master/lib/kitchen/driver/azure_credentials.rb#L95 as well as possibly updating to the latest MSRest gem which is a transitive dependency inside the SDK.

I agree it would be a good enhancement.
